from flask import Flask, request, jsonify, Response

app = Flask(__name__)

# -------------------------------
# FRONTEND UI (Upgraded v11)
# -------------------------------
html_ui = """
<!DOCTYPE html>
<html>
<head>
<title>AI App Builder v11</title>
<style>
body { font-family: Arial; padding: 20px; background: #e9eef5; }
textarea { width: 100%; padding: 10px; font-size: 16px; }
button { padding: 10px 20px; font-size: 16px; margin-top: 10px; cursor: pointer; }
#container { display: flex; gap: 20px; }
#output, #preview {
    white-space: pre-wrap; background: white; padding: 15px;
    margin-top: 20px; border-radius: 6px;
}
#output { width: 50%; }
#preview { width: 50%; border: 2px dashed #888; min-height: 200px; }
</style>
</head>
<body>
<h2>AI App Builder v11</h2>
<textarea id="prompt" rows="5" placeholder="Describe the app, business or marketing tool"></textarea><br>
<button onclick="generate()">Generate</button>

<div id="container">
    <div id="output">Generated Code Will Appear Here...</div>
    <div id="preview">Preview Will Appear Here...</div>
</div>

<script>
function generate() {
    let text = document.getElementById('prompt').value;

    fetch('/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: text })
    })
    .then(res => res.json())
    .then(data => {
        document.getElementById('output').innerText = data.code;
        document.getElementById('preview').innerHTML = data.preview;
    })
    .catch(err => alert('Error: ' + err));
}
</script>
</body>
</html>
"""

# ============================================
#   ULTRA DIGITAL EMPIRE v3
#   Real Website / App Builder + Deployment
# ============================================

from flask import Flask, request, jsonify, Response
import os, json, random, time
from datetime import datetime

# -------------------------------------------------
# (1) AI CONTENT GENERATOR
# -------------------------------------------------
def generate_content(topic):
    return {
        "caption": f"{topic} — Generated by ULTRA Digital Empire",
        "hashtags": "#ai #marketing #autopost #digitalempire",
        "script": f"Intro: Today we talk about {topic}...\nScene 1...\nScene 2..."
    }

# -------------------------------------------------
# (2) ADS GENERATOR
# -------------------------------------------------
def generate_ads(platform, product):
    return f"🔥 Check out {product} on {platform}! Best deals and offers! #ad #promo #digitalempire"

# -------------------------------------------------
# (3) REAL WEBSITE / APP BUILDER
# -------------------------------------------------
def build_real_website(business, industry, features=None):
    """Builds a real HTML/CSS/JS website with optional features."""
    os.makedirs("sites", exist_ok=True)
    features_html = ""
    if features:
        for f in features:
            features_html += f"<li>{f}</li>\n"

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{business} - {industry}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; }}
            header {{ background: #0d6efd; color: white; padding: 20px; text-align: center; }}
            section {{ padding: 20px; }}
            ul {{ list-style: disc; padding-left: 20px; }}
            footer {{ background: #333; color: white; padding: 10px; text-align: center; }}
            a.button {{ display:inline-block; padding:10px 20px; background:#0d6efd; color:white; text-decoration:none; border-radius:5px; }}
        </style>
    </head>
    <body>
        <header>
            <h1>{business}</h1>
            <p>Industry: {industry}</p>
        </header>
        <section>
            <h2>Welcome to {business}</h2>
            <p>We provide the best {industry} services for your needs.</p>
            {f"<ul>{features_html}</ul>" if features_html else ""}
            <a href="https://wa.me/23270000000" class="button">Chat on WhatsApp</a>
        </section>
        <footer>
            &copy; {datetime.now().year} {business} - Powered by ULTRA Digital Empire
        </footer>
    </body>
    </html>
    """
    path = f"sites/{business.replace(' ','_').lower()}.html"
    with open(path, "w") as f:
        f.write(html)
    return path

# -------------------------------------------------
# (4) AUTO DEPLOY (Simulated Free Domain)
# -------------------------------------------------
def auto_deploy(path):
    subdomain = f"{random.randint(1000,9999)}-{os.path.basename(path).split('.')[0]}.ultradigital.app"
    # In reality: you can push sites folder to Netlify / Replit / Vercel via API
    return f"https://{subdomain}"

# -------------------------------------------------
# (5) SOCIAL MEDIA AUTOMATION
# -------------------------------------------------
def social_post(platform, content):
    return f"✅ Posted on {platform}: {content[:50]}..."

# -------------------------------------------------
# (6) BUSINESS BUILDER
# -------------------------------------------------
BUSINESS_FILE = "business.json"
if not os.path.exists(BUSINESS_FILE):
    open(BUSINESS_FILE, "w").write("[]")

def add_business(name, industry):
    businesses = json.load(open(BUSINESS_FILE))
    businesses.append({"name": name, "industry": industry, "created": str(datetime.now())})
    json.dump(businesses, open(BUSINESS_FILE, "w"))
    return "Business Added"

def get_businesses():
    return json.load(open(BUSINESS_FILE))

# -------------------------------------------------
# (7) SMART AI ASSISTANT
# -------------------------------------------------
def ai_assistant(task):
    tips = [
        "Post consistently on social media.",
        "Use AI-generated content to save time.",
        "Automate repetitive tasks.",
        "Focus on high ROI marketing channels.",
        "Test multiple ad campaigns for better results."
    ]
    return {"task": task, "advice": random.choice(tips)}

# -------------------------------------------------
# (8) DIGITAL MARKETING GENERATOR
# -------------------------------------------------
def marketing_plan(business):
    return {
        "strategy": f"Promote {business} on social media, email campaigns, and Google Ads.",
        "hashtags": "#marketing #ai #digitalempire",
        "ad_idea": f"Launch a special offer for {business} this week!"
    }

# -------------------------------------------------
# (9) AUTOMATION ENGINE
# -------------------------------------------------
def run_automation(task_name):
    return f"Automation Task '{task_name}' executed successfully!"

# -------------------------------------------------
# (10) FLASK APP
# -------------------------------------------------
app = Flask(_name_)

@app.route("/")
def home():
    return Response("<h1>ULTRA DIGITAL EMPIRE v3</h1><p>All systems online. Real websites and apps supported.</p>", mimetype="text/html")

# -------------------------------
# AI CONTENT
# -------------------------------
@app.post("/generate")
def gen():
    topic = request.json["topic"]
    return jsonify(generate_content(topic))

# -------------------------------
# ADS GENERATOR
# -------------------------------
@app.post("/ads")
def ads():
    data = request.json
    return jsonify({"ad": generate_ads(data["platform"], data["product"])})

# -------------------------------
# BUILD REAL WEBSITE / APP
# -------------------------------
@app.post("/buildsite")
def buildsite():
    d = request.json
    path = build_real_website(d["business"], d["industry"], d.get("features"))
    url = auto_deploy(path)
    return jsonify({"file": path, "url": url})

# -------------------------------
# SOCIAL MEDIA POST
# -------------------------------
@app.post("/socialpost")
def sm_post():
    data = request.json
    return jsonify({"status": social_post(data["platform"], data["content"])})

# -------------------------------
# BUSINESS BUILDER
# -------------------------------
@app.post("/addbusiness")
def addbiz():
    data = request.json
    return jsonify({"status": add_business(data["name"], data["industry"])})

@app.get("/businesses")
def all_businesses():
    return jsonify(get_businesses())

# -------------------------------
# AI ASSISTANT
# -------------------------------
@app.post("/assistant")
def assistant():
    task = request.json["task"]
    return jsonify(ai_assistant(task))

# -------------------------------
# DIGITAL MARKETING
# -------------------------------
@app.post("/marketing")
def marketing():
    business = request.json["business"]
    return jsonify(marketing_plan(business))

# -------------------------------
# AUTOMATION ENGINE
# -------------------------------
@app.post("/automation")
def automation():
    task = request.json["task"]
    return jsonify({"status": run_automation(task)})

# -------------------------------
# RUN
# -------------------------------
if _name_ == "_main_":
    app.run(host="0.0.0.0", port=5000)